[tool.ruff]
line-length = 80
[tool.ruff.format]
quote-style = "single"
[tool.ruff.lint]
select = ["Q", "E", "F", "W", "I", "C", "B"]
ignore = ["D", "INP001"]

[tool.ruff.lint.flake8-quotes]
inline-quotes = "single"
multiline-quotes = "double"
docstring-quotes = "double"
